name: "release"
on:
  push:
    branches:
      - "UltraPack"
jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'UltraPack.zip'
        exclusions: '*.git* profileImage/* README.md CODE_OF_CONDUCT.md LICENSE TLauncherAdditional.json UltraPack.jar UltraPack.json'
    - name: Upload Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "Technic"
        prerelease: false
        title: "Technic UltraPack 1.16.5"
        files: 'UltraPack.zip'
